apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build

on:
  push:
    branches:
    - '**'
permissions:
  scm-token-own: read
  scm-token-org: read
jobs:
  run-unit-test:
    steps:
      - name: Get sourcecode
        uses: cloudbees-io/checkout@v1
      - id: build
        name: Run Unit test
        uses: calculi-corp/cb-internal-shared-actions/build@v1
        with:
          go-binary-build: "false"
          kaniko-build: "false"
          trivy-scan-container: "false"
          bundled-sonar-scan: "true"
          snyk-org-name: ${{ vars.SNYK_SAAS_ORG_NAME }}
          snyk-saas-token: ${{ secrets.SNYK_SAAS_TOKEN }}