apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build
on:
  push:
    branches:
      - "**"
permissions:
  scm-token-own: read
  scm-token-org: read
jobs:
  run-unit-test:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Get sourcecode
        with:
          provider: GitHub
          repository: https://github.com/naqsh01-workshop/jpetstore-6.git
          ref: master
          token: ${{ secrets.SNAQVI_GITHUB_SECRET }}
      - uses: calculi-corp/cb-internal-shared-actions/build@v1
        name: Run Unit test
        id: build
        with:
          go-binary-build: "false"
          kaniko-build: "false"
          trivy-scan-container: "false"
          bundled-sonar-scan: "true"
