apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: cloudbees-io/cbci-run-job@v2
        name: Build
        kind: build
        with:
          url: https://sda.preview.cb-demos.io/snaqvi-cbdemos/
          username: snaqvi
          token: 11a963b9640989c575bcfb04afc2f65619
          job-name: Pet%20Store%20Pipeline
          test-type: Junit
          test-result-location: testReport
  scan:
    steps:
      - uses: cloudbees-io/sonarqube-sast-scan-code@v1
        name: Scan
        kind: scan
        with:
          server-url: https://sonarqube.cb-demos.io/dashboard?id=petclinic
          username: admin
          password: admin123
          language: Java
  TriggerCloudBeesCD:
    steps:
      - uses: docker://alpine:3.18
        shell: sh
        run: |
          curl -X POST "https://sda.preview.cb-demos.io/rest/v1.0/releases?projectName=snaqvi%20Demo&releaseName=AWS%20Release" -H "accept: application/json" -d "{}"
    needs: scan
